import React, { useState } from 'react';
import { ShieldCheck, CheckCircle, XCircle, AlertCircle, HelpCircle, Info } from 'lucide-react';
import { Card, Badge, Breadcrumb, Button, ConfidenceBadge, VerificationBadge, Alert } from '@/design-system';
import { mockDrafts } from '@/services/api/mockData';

// ── Verification claim card ───────────────────────────────────────────────────

function ClaimCard({ claim }: { claim: NonNullable<typeof mockDrafts[0]['verifications']>[0] }) {
  const statusIcons: Record<string, React.ReactNode> = {
    verified: <CheckCircle className="w-4 h-4 text-green-600" />,
    partial: <AlertCircle className="w-4 h-4 text-amber-500" />,
    unsupported: <XCircle className="w-4 h-4 text-red-500" />,
    contradicted: <XCircle className="w-4 h-4 text-red-700" />,
    pending: <HelpCircle className="w-4 h-4 text-gray-400" />,
  };

  const statusBg: Record<string, string> = {
    verified: 'border-green-200 bg-green-50',
    partial: 'border-amber-200 bg-amber-50',
    unsupported: 'border-red-200 bg-red-50',
    contradicted: 'border-red-300 bg-red-100',
    pending: 'border-gray-200 bg-gray-50',
  };

  return (
    <div className={`p-4 rounded-[10px] border ${statusBg[claim.status] ?? 'border-gray-200'}`}>
      <div className="flex items-start gap-3">
        <div className="mt-0.5 shrink-0">{statusIcons[claim.status]}</div>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-1.5 flex-wrap">
            <VerificationBadge status={claim.status} />
            <ConfidenceBadge score={claim.confidence} />
          </div>

          <blockquote className="text-sm text-ink font-medium leading-snug mb-2">
            "{claim.claim}"
          </blockquote>

          {claim.reason && (
            <div className="flex items-start gap-1.5 text-xs text-amber-700 mb-2">
              <Info className="w-3 h-3 mt-0.5 shrink-0" />
              {claim.reason}
            </div>
          )}

          {claim.sources && claim.sources.length > 0 && (
            <div>
              <p className="text-xs text-ink-secondary font-medium mb-1">Sources:</p>
              <div className="flex flex-wrap gap-1.5">
                {claim.sources.map((s) => (
                  <Badge key={s} variant="neutral" size="sm">{s}</Badge>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Verification Page ─────────────────────────────────────────────────────────

export function VerificationPage() {
  const draft = mockDrafts[0];
  const verifications = draft.verifications ?? [];

  const counts = {
    verified: verifications.filter((v) => v.status === 'verified').length,
    partial: verifications.filter((v) => v.status === 'partial').length,
    unsupported: verifications.filter((v) => v.status === 'unsupported').length,
    contradicted: verifications.filter((v) => v.status === 'contradicted').length,
    pending: verifications.filter((v) => v.status === 'pending').length,
  };

  const [filter, setFilter] = useState<string>('all');

  const filtered = filter === 'all'
    ? verifications
    : verifications.filter((v) => v.status === filter);

  return (
    <div className="space-y-5 max-w-3xl">
      <div>
        <Breadcrumb items={[{ label: 'AI Workspace' }, { label: 'Verification' }]} />
        <h1 className="text-2xl font-bold text-ink mt-1">Verification</h1>
        <p className="text-sm text-ink-secondary">Fact-checking and claim verification for AI-generated content</p>
      </div>

      {/* Info alert */}
      <Alert variant="info">
        <p className="font-medium">About Verification</p>
        <p>Each claim is checked against retrieved legal evidence. The Hallucination Classifier model is under development — current checks use rule-based and retrieval methods.</p>
      </Alert>

      {/* Draft context */}
      <Card>
        <div className="flex items-start gap-3">
          <ShieldCheck className="w-5 h-5 text-primary-700 mt-0.5 shrink-0" />
          <div>
            <p className="font-semibold text-ink">{draft.title}</p>
            <p className="text-sm text-ink-secondary">Generated by {draft.agentUsed} · {draft.modelUsed}</p>
          </div>
          <div className="ml-auto">
            <ConfidenceBadge score={draft.overallConfidence ?? 0} />
          </div>
        </div>
      </Card>

      {/* Summary stats */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
        {[
          { label: 'Verified', count: counts.verified, color: 'text-green-700 bg-green-50 border-green-200' },
          { label: 'Partial', count: counts.partial, color: 'text-amber-700 bg-amber-50 border-amber-200' },
          { label: 'Unsupported', count: counts.unsupported, color: 'text-red-700 bg-red-50 border-red-200' },
          { label: 'Contradicted', count: counts.contradicted, color: 'text-red-800 bg-red-100 border-red-300' },
          { label: 'Pending', count: counts.pending, color: 'text-gray-600 bg-gray-50 border-gray-200' },
        ].map((s) => (
          <div key={s.label} className={`px-3 py-2 rounded-[8px] border text-center ${s.color}`}>
            <p className="text-2xl font-bold">{s.count}</p>
            <p className="text-xs font-medium">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Filter tabs */}
      <div className="flex gap-2 flex-wrap">
        {['all', 'verified', 'partial', 'unsupported', 'contradicted'].map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-3 py-1.5 text-sm rounded-[6px] font-medium transition-colors ${
              filter === f
                ? 'bg-primary-400 text-primary-900'
                : 'bg-surface-raised border border-border text-ink-secondary hover:border-border-strong'
            }`}
          >
            {f === 'all' ? 'All Claims' : f.charAt(0).toUpperCase() + f.slice(1)}
            {f === 'all' && ` (${verifications.length})`}
          </button>
        ))}
      </div>

      {/* Claims list */}
      <div className="space-y-3">
        {filtered.length === 0 ? (
          <p className="text-center text-sm text-ink-secondary py-8">No claims match this filter.</p>
        ) : (
          filtered.map((v) => <ClaimCard key={v.claimId} claim={v} />)
        )}
      </div>
    </div>
  );
}
