import type {
  Case, Document, Draft, ResearchResult, Hearing, Task,
  TimelineEvent, AgentExecution, AIModel, Client, Notification,
  AnalyticsOverview, User,
} from '@/types';

// ── Helpers ───────────────────────────────────────────────────────────────────

function iso(daysFromNow: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString();
}

function past(daysAgo: number): string {
  return iso(-daysAgo);
}

// ── Users ─────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Arjun Sharma',
    email: 'arjun@axiomlaw.in',
    role: 'lawyer',
    organization: 'Axiom Law Associates',
    barCouncilId: 'DL/2015/12345',
    createdAt: past(365),
    updatedAt: past(1),
    isActive: true,
  },
  {
    id: 'u2',
    name: 'Priya Mehta',
    email: 'priya@axiomlaw.in',
    role: 'admin',
    organization: 'Axiom Law Associates',
    createdAt: past(400),
    updatedAt: past(2),
    isActive: true,
  },
  {
    id: 'u3',
    name: 'Rahul Verma',
    email: 'rahul@axiomlaw.in',
    role: 'junior',
    organization: 'Axiom Law Associates',
    createdAt: past(180),
    updatedAt: past(3),
    isActive: true,
  },
  {
    id: 'u4',
    name: 'Demo Lawyer',
    email: 'demo@jurispulse.in',
    role: 'lawyer',
    organization: 'JurisPulse Demo',
    barCouncilId: 'MH/2018/67890',
    createdAt: past(200),
    updatedAt: past(1),
    isActive: true,
  },
];

export const mockCurrentUser = mockUsers[3];

// ── Cases ─────────────────────────────────────────────────────────────────────

export const mockCases: Case[] = [
  {
    id: 'c1',
    caseNumber: 'WP(C)/2024/00345',
    title: 'Ramesh Kumar vs. Union of India',
    caseType: 'writ',
    court: 'Delhi High Court',
    jurisdiction: 'Delhi',
    filingDate: past(120),
    status: 'active',
    priority: 'high',
    parties: [
      { id: 'p1', name: 'Ramesh Kumar', role: 'petitioner' },
      { id: 'p2', name: 'Union of India', role: 'respondent' },
    ],
    clientId: 'cl1',
    clientName: 'Ramesh Kumar',
    assignedLawyers: ['u1', 'u3'],
    description: 'Writ petition challenging arbitrary transfer orders issued by the Ministry of Railways.',
    tags: ['service law', 'transfer', 'writ'],
    nextHearing: iso(5),
    deadlineDate: iso(12),
    riskLevel: 'medium',
    createdAt: past(120),
    updatedAt: past(1),
  },
  {
    id: 'c2',
    caseNumber: 'CC/2024/01122',
    title: 'Sharma Builders vs. Anita Gupta',
    caseType: 'consumer',
    court: 'Consumer Forum, South Delhi',
    jurisdiction: 'Delhi',
    filingDate: past(60),
    status: 'pending',
    priority: 'medium',
    parties: [
      { id: 'p3', name: 'Sharma Builders Pvt. Ltd.', role: 'respondent' },
      { id: 'p4', name: 'Anita Gupta', role: 'petitioner' },
    ],
    clientId: 'cl2',
    clientName: 'Sharma Builders Pvt. Ltd.',
    assignedLawyers: ['u1'],
    description: 'Consumer complaint regarding delayed possession and deficiency in service.',
    tags: ['consumer', 'real estate', 'possession'],
    nextHearing: iso(14),
    riskLevel: 'low',
    createdAt: past(60),
    updatedAt: past(5),
  },
  {
    id: 'c3',
    caseNumber: 'CRL.REV.P/2024/0089',
    title: 'State vs. Vikas Nair',
    caseType: 'criminal',
    court: 'Delhi High Court',
    jurisdiction: 'Delhi',
    filingDate: past(200),
    status: 'active',
    priority: 'critical',
    parties: [
      { id: 'p5', name: 'State of Delhi', role: 'petitioner' },
      { id: 'p6', name: 'Vikas Nair', role: 'respondent' },
    ],
    clientId: 'cl3',
    clientName: 'Vikas Nair',
    assignedLawyers: ['u1', 'u3'],
    description: 'Criminal revision petition in bail matter. Accused in custody.',
    tags: ['criminal', 'bail', 'revision'],
    nextHearing: iso(2),
    deadlineDate: iso(3),
    riskLevel: 'high',
    createdAt: past(200),
    updatedAt: past(1),
  },
  {
    id: 'c4',
    caseNumber: 'FAO/2023/0456',
    title: 'M/s Tara Exports vs. HDFC Bank Ltd.',
    caseType: 'civil',
    court: 'Delhi High Court',
    jurisdiction: 'Delhi',
    filingDate: past(300),
    status: 'active',
    priority: 'high',
    parties: [
      { id: 'p7', name: 'M/s Tara Exports', role: 'appellant' },
      { id: 'p8', name: 'HDFC Bank Ltd.', role: 'respondent' },
    ],
    clientId: 'cl4',
    clientName: 'M/s Tara Exports',
    assignedLawyers: ['u1'],
    description: 'First appeal from decree in a commercial recovery suit.',
    tags: ['civil', 'commercial', 'banking'],
    nextHearing: iso(20),
    riskLevel: 'medium',
    createdAt: past(300),
    updatedAt: past(3),
  },
  {
    id: 'c5',
    caseNumber: 'CS(COMM)/2024/00789',
    title: 'TechNova Solutions vs. Kapoor & Co.',
    caseType: 'corporate',
    court: 'Delhi High Court',
    jurisdiction: 'Delhi',
    filingDate: past(45),
    status: 'active',
    priority: 'medium',
    parties: [
      { id: 'p9', name: 'TechNova Solutions Pvt. Ltd.', role: 'plaintiff' },
      { id: 'p10', name: 'Kapoor & Co.', role: 'defendant' },
    ],
    clientId: 'cl5',
    clientName: 'TechNova Solutions Pvt. Ltd.',
    assignedLawyers: ['u1', 'u3'],
    description: 'Commercial suit for recovery of dues under software services agreement.',
    tags: ['corporate', 'commercial', 'IP'],
    nextHearing: iso(30),
    riskLevel: 'low',
    createdAt: past(45),
    updatedAt: past(2),
  },
  {
    id: 'c6',
    caseNumber: 'MAT.APP/2022/0123',
    title: 'Deepa Rao vs. Suresh Rao',
    caseType: 'family',
    court: 'Family Court, Saket',
    jurisdiction: 'Delhi',
    filingDate: past(500),
    status: 'closed',
    priority: 'low',
    parties: [
      { id: 'p11', name: 'Deepa Rao', role: 'petitioner' },
      { id: 'p12', name: 'Suresh Rao', role: 'respondent' },
    ],
    clientId: 'cl6',
    clientName: 'Deepa Rao',
    assignedLawyers: ['u1'],
    description: 'Matrimonial appeal arising from divorce decree.',
    tags: ['family', 'matrimonial', 'divorce'],
    riskLevel: 'low',
    createdAt: past(500),
    updatedAt: past(30),
  },
];

// ── Documents ─────────────────────────────────────────────────────────────────

export const mockDocuments: Document[] = [
  {
    id: 'd1',
    title: 'Writ Petition — Ramesh Kumar vs UoI',
    fileName: 'writ_petition_ramesh_kumar.pdf',
    fileSize: 245000,
    fileType: 'application/pdf',
    documentType: 'petition',
    caseId: 'c1',
    caseName: 'Ramesh Kumar vs. Union of India',
    status: 'verified',
    tags: ['petition', 'service law'],
    entities: [
      { type: 'person', value: 'Ramesh Kumar', confidence: 0.98 },
      { type: 'act', value: 'Railway Services Conduct Rules', confidence: 0.92 },
      { type: 'section', value: 'Article 226', confidence: 0.97 },
      { type: 'date', value: '15 January 2024', confidence: 0.99 },
    ],
    uploadedBy: 'u1',
    uploadedAt: past(110),
    processedAt: past(109),
    version: 2,
  },
  {
    id: 'd2',
    title: 'Counter Affidavit — UoI Response',
    fileName: 'counter_affidavit_uoi.pdf',
    fileSize: 180000,
    fileType: 'application/pdf',
    documentType: 'affidavit',
    caseId: 'c1',
    caseName: 'Ramesh Kumar vs. Union of India',
    status: 'processed',
    tags: ['affidavit', 'government'],
    uploadedBy: 'u3',
    uploadedAt: past(80),
    processedAt: past(79),
    version: 1,
  },
  {
    id: 'd3',
    title: 'Consumer Complaint — Sharma Builders',
    fileName: 'consumer_complaint_sharma.pdf',
    fileSize: 120000,
    fileType: 'application/pdf',
    documentType: 'complaint',
    caseId: 'c2',
    caseName: 'Sharma Builders vs. Anita Gupta',
    status: 'needs_review',
    tags: ['complaint', 'consumer'],
    uploadedBy: 'u1',
    uploadedAt: past(58),
    processedAt: past(57),
    version: 1,
  },
  {
    id: 'd4',
    title: 'Bail Application — Vikas Nair',
    fileName: 'bail_application_vikas_nair.docx',
    fileSize: 85000,
    fileType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    documentType: 'bail_application',
    caseId: 'c3',
    caseName: 'State vs. Vikas Nair',
    status: 'verified',
    tags: ['bail', 'criminal'],
    uploadedBy: 'u1',
    uploadedAt: past(5),
    processedAt: past(5),
    version: 3,
  },
  {
    id: 'd5',
    title: 'Evidence Bundle — Transfer Orders',
    fileName: 'evidence_transfer_orders.pdf',
    fileSize: 450000,
    fileType: 'application/pdf',
    documentType: 'evidence',
    caseId: 'c1',
    caseName: 'Ramesh Kumar vs. Union of India',
    status: 'processing',
    tags: ['evidence', 'government order'],
    uploadedBy: 'u3',
    uploadedAt: past(1),
    version: 1,
  },
];

// ── Drafts ────────────────────────────────────────────────────────────────────

export const mockDrafts: Draft[] = [
  {
    id: 'dr1',
    title: 'Bail Application — Vikas Nair (v3)',
    draftType: 'bail_application',
    caseId: 'c3',
    caseName: 'State vs. Vikas Nair',
    content: `IN THE HIGH COURT OF DELHI AT NEW DELHI\n\nCRIMINAL REVISION PETITION NO. CRL.REV.P/2024/0089\n\nIN THE MATTER OF:\nState of Delhi ... Petitioner\n\nVERSUS\n\nVikas Nair s/o Ramkishore Nair ... Respondent/Accused\n\nAPPLICATION FOR BAIL UNDER SECTION 439 CrPC\n\n1. That the applicant Vikas Nair has been in judicial custody since 12.03.2024 and is presently lodged in Tihar Jail, Delhi.\n\n2. That the applicant is a first-time offender with no prior criminal antecedents.\n\n3. That the allegations against the applicant do not prima facie establish the commission of a heinous offence...`,
    status: 'reviewing',
    agentUsed: 'Legal Drafter Agent',
    modelUsed: 'Llama 3.1 Legal Drafter',
    verifications: [
      {
        claimId: 'v1',
        claim: 'The applicant has been in judicial custody since 12.03.2024',
        status: 'verified',
        confidence: 0.94,
        sources: ['Court records', 'Remand application'],
      },
      {
        claimId: 'v2',
        claim: 'The applicant is a first-time offender with no prior criminal antecedents',
        status: 'partial',
        confidence: 0.67,
        reason: 'Police verification report pending',
        sources: ['Affidavit of accused'],
      },
      {
        claimId: 'v3',
        claim: 'Section 439 CrPC governs bail from High Court',
        status: 'verified',
        confidence: 0.99,
        sources: ['Code of Criminal Procedure, 1973'],
      },
    ],
    overallConfidence: 0.82,
    createdBy: 'u1',
    createdAt: past(3),
    updatedAt: past(1),
  },
  {
    id: 'dr2',
    title: 'Legal Notice — Sharma Builders (Draft)',
    draftType: 'legal_notice',
    caseId: 'c2',
    caseName: 'Sharma Builders vs. Anita Gupta',
    content: `LEGAL NOTICE\n\nTo,\nM/s. Sharma Builders Pvt. Ltd.\n...\n\nThis notice is issued on behalf of Mrs. Anita Gupta...`,
    status: 'draft',
    agentUsed: 'Legal Drafter Agent',
    modelUsed: 'Llama 3.1 Legal Drafter',
    overallConfidence: 0.91,
    createdBy: 'u1',
    createdAt: past(7),
    updatedAt: past(6),
  },
];

// ── Research Results ──────────────────────────────────────────────────────────

export const mockResearchResults: ResearchResult[] = [
  {
    id: 'r1',
    caseTitle: 'Satender Kumar Antil vs. Central Bureau of Investigation',
    citation: '2022 SCC OnLine SC 825',
    court: 'Supreme Court of India',
    date: '2022-07-11',
    judges: ['S. Abdul Nazeer J.', 'Vikram Nath J.'],
    summary: 'Landmark judgment laying down guidelines for bail in cases involving non-heinous offences and reducing overcrowding in jails.',
    relevantPassage: 'The courts ought to be more liberal in granting bail in offences which are not heinous in nature and the accused is a first-time offender without any criminal antecedents...',
    similarityScore: 0.91,
    acts: ['Code of Criminal Procedure, 1973'],
    sections: ['Section 437', 'Section 439', 'Section 167(2)'],
    keywords: ['bail', 'first offender', 'liberal approach', 'pre-trial detention'],
    outcome: 'Guidelines issued',
  },
  {
    id: 'r2',
    caseTitle: 'Arnesh Kumar vs. State of Bihar',
    citation: '(2014) 8 SCC 273',
    court: 'Supreme Court of India',
    date: '2014-07-02',
    judges: ['Chandramauli Kr. Prasad J.', 'Pinaki Chandra Ghose J.'],
    summary: 'Directions to magistrates and police on arrest of accused in cases punishable with imprisonment up to 7 years.',
    relevantPassage: 'The power of arrest is one of the lucrative sources of police corruption. Before arresting a person, a police officer must justify the necessity of arrest...',
    similarityScore: 0.87,
    acts: ['Code of Criminal Procedure, 1973', 'Indian Penal Code'],
    sections: ['Section 41', 'Section 498A'],
    keywords: ['arrest', 'police power', 'necessity', 'first offender'],
    outcome: 'Guidelines issued for arrest procedure',
  },
  {
    id: 'r3',
    caseTitle: 'Sushila Aggarwal vs. State (NCT of Delhi)',
    citation: '(2020) 5 SCC 1',
    court: 'Supreme Court of India',
    date: '2020-01-29',
    relevantPassage: 'Anticipatory bail can be granted for a specific period and it is not necessary to limit it to the period up to filing of chargesheet.',
    similarityScore: 0.79,
    acts: ['Code of Criminal Procedure, 1973'],
    sections: ['Section 438'],
    keywords: ['anticipatory bail', 'duration', 'period'],
  },
];

// ── Hearings ──────────────────────────────────────────────────────────────────

export const mockHearings: Hearing[] = [
  {
    id: 'h1',
    caseId: 'c3',
    caseName: 'State vs. Vikas Nair',
    caseNumber: 'CRL.REV.P/2024/0089',
    court: 'Delhi High Court',
    date: iso(2),
    time: '10:30',
    purpose: 'Hearing on bail application',
    judge: 'Justice Prathiba M. Singh',
    status: 'scheduled',
    notes: 'Bail application filed. Counter required from State.',
    createdAt: past(5),
  },
  {
    id: 'h2',
    caseId: 'c1',
    caseName: 'Ramesh Kumar vs. Union of India',
    caseNumber: 'WP(C)/2024/00345',
    court: 'Delhi High Court',
    date: iso(5),
    time: '02:00',
    purpose: 'Arguments on merits',
    status: 'scheduled',
    createdAt: past(10),
  },
  {
    id: 'h3',
    caseId: 'c2',
    caseName: 'Sharma Builders vs. Anita Gupta',
    caseNumber: 'CC/2024/01122',
    court: 'Consumer Forum, South Delhi',
    date: iso(14),
    time: '11:00',
    purpose: 'Evidence recording',
    status: 'scheduled',
    createdAt: past(20),
  },
  {
    id: 'h4',
    caseId: 'c1',
    caseName: 'Ramesh Kumar vs. Union of India',
    caseNumber: 'WP(C)/2024/00345',
    court: 'Delhi High Court',
    date: past(15),
    time: '10:30',
    purpose: 'Admission hearing',
    status: 'completed',
    outcome: 'Petition admitted. Notice issued to respondent.',
    nextAction: 'File counter affidavit within 4 weeks.',
    createdAt: past(30),
  },
];

// ── Tasks ─────────────────────────────────────────────────────────────────────

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Prepare bail arguments for Vikas Nair hearing',
    description: 'Draft key points for bail arguments. Focus on Satender Kumar Antil guidelines.',
    caseId: 'c3',
    caseName: 'State vs. Vikas Nair',
    assigneeId: 'u1',
    assigneeName: 'Arjun Sharma',
    priority: 'critical',
    dueDate: iso(1),
    status: 'in_progress',
    createdBy: 'u1',
    createdAt: past(5),
    updatedAt: past(1),
  },
  {
    id: 't2',
    title: 'File evidence bundle for Ramesh Kumar case',
    caseId: 'c1',
    caseName: 'Ramesh Kumar vs. Union of India',
    assigneeId: 'u3',
    assigneeName: 'Rahul Verma',
    priority: 'high',
    dueDate: iso(4),
    status: 'todo',
    createdBy: 'u1',
    createdAt: past(3),
    updatedAt: past(3),
  },
  {
    id: 't3',
    title: 'Review consumer complaint draft — Sharma Builders',
    caseId: 'c2',
    caseName: 'Sharma Builders vs. Anita Gupta',
    assigneeId: 'u1',
    assigneeName: 'Arjun Sharma',
    priority: 'medium',
    dueDate: iso(7),
    status: 'waiting',
    createdBy: 'u1',
    createdAt: past(10),
    updatedAt: past(8),
  },
  {
    id: 't4',
    title: 'Research precedents for TechNova IP dispute',
    caseId: 'c5',
    caseName: 'TechNova Solutions vs. Kapoor & Co.',
    assigneeId: 'u3',
    assigneeName: 'Rahul Verma',
    priority: 'medium',
    dueDate: iso(10),
    status: 'todo',
    createdBy: 'u1',
    createdAt: past(2),
    updatedAt: past(2),
  },
  {
    id: 't5',
    title: 'Client call — Ramesh Kumar update',
    caseId: 'c1',
    caseName: 'Ramesh Kumar vs. Union of India',
    assigneeId: 'u1',
    assigneeName: 'Arjun Sharma',
    priority: 'low',
    dueDate: past(1),
    status: 'completed',
    createdBy: 'u1',
    createdAt: past(5),
    updatedAt: past(1),
    completedAt: past(1),
  },
];

// ── Timeline Events ───────────────────────────────────────────────────────────

export const mockTimelineEvents: TimelineEvent[] = [
  {
    id: 'te1',
    caseId: 'c1',
    type: 'filing',
    title: 'Writ Petition Filed',
    description: 'WP(C) filed challenging arbitrary transfer order.',
    date: past(120),
    documentId: 'd1',
    documentName: 'Writ Petition — Ramesh Kumar vs UoI',
    createdBy: 'u1',
    createdAt: past(120),
  },
  {
    id: 'te2',
    caseId: 'c1',
    type: 'hearing',
    title: 'Admission Hearing',
    description: 'Petition admitted. Notice issued to Union of India.',
    date: past(90),
    source: 'Court Order',
    createdBy: 'u1',
    createdAt: past(90),
  },
  {
    id: 'te3',
    caseId: 'c1',
    type: 'notice',
    title: 'Notice Served to Respondent',
    description: 'Notice served to Ministry of Railways.',
    date: past(85),
    createdBy: 'u3',
    createdAt: past(85),
  },
  {
    id: 'te4',
    caseId: 'c1',
    type: 'reply',
    title: 'Counter Affidavit Filed by UoI',
    description: 'Union of India filed counter affidavit denying allegations.',
    date: past(50),
    documentId: 'd2',
    documentName: 'Counter Affidavit — UoI Response',
    createdBy: 'u1',
    createdAt: past(50),
  },
  {
    id: 'te5',
    caseId: 'c1',
    type: 'hearing',
    title: 'Arguments Scheduled',
    description: 'Next date fixed for final arguments on merits.',
    date: iso(5),
    createdBy: 'u1',
    createdAt: past(15),
  },
];

// ── Agent Executions ──────────────────────────────────────────────────────────

export const mockAgentExecutions: AgentExecution[] = [
  {
    id: 'ae1',
    agentId: 'agent-intake',
    agentName: 'Case Intake Agent',
    caseId: 'c3',
    input: { caseId: 'c3', documents: ['d4'] },
    output: { summary: 'Criminal revision in bail matter. Accused in custody since March 2024.' },
    status: 'completed',
    startedAt: past(3),
    completedAt: past(3),
    durationMs: 1240,
    confidence: 0.93,
  },
  {
    id: 'ae2',
    agentId: 'agent-doc-review',
    agentName: 'Document Review Agent',
    caseId: 'c3',
    input: { documentIds: ['d4'] },
    output: { entities: 12, flags: 0, sections: ['Section 439 CrPC'] },
    status: 'completed',
    startedAt: past(3),
    completedAt: past(3),
    durationMs: 3450,
    confidence: 0.91,
  },
  {
    id: 'ae3',
    agentId: 'agent-research',
    agentName: 'Research Agent',
    caseId: 'c3',
    input: { query: 'bail first offender criminal revision', k: 10 },
    output: { results: 10, topScore: 0.91 },
    status: 'completed',
    startedAt: past(2),
    completedAt: past(2),
    durationMs: 8900,
    sources: ['Satender Kumar Antil (2022)', 'Arnesh Kumar (2014)'],
    confidence: 0.89,
  },
  {
    id: 'ae4',
    agentId: 'agent-drafting',
    agentName: 'Drafting Agent',
    caseId: 'c3',
    input: { draftType: 'bail_application', caseId: 'c3' },
    output: { draftId: 'dr1', wordCount: 1240 },
    status: 'completed',
    startedAt: past(1),
    completedAt: past(1),
    durationMs: 18200,
    confidence: 0.82,
  },
  {
    id: 'ae5',
    agentId: 'agent-verification',
    agentName: 'Verification Agent',
    caseId: 'c3',
    input: { draftId: 'dr1' },
    status: 'running',
    startedAt: new Date().toISOString(),
    confidence: undefined,
  },
];

// ── AI Models ─────────────────────────────────────────────────────────────────

export const mockAIModels: AIModel[] = [
  {
    id: 'llama-3-1-legal',
    name: 'Llama 3.1 Legal Drafter',
    purpose: 'Legal document drafting',
    version: '3.1',
    provider: 'Meta (Fine-tuned)',
    status: 'available',
    latencyMs: 4200,
    usageCount: 1247,
    lastUpdated: past(14),
    description: 'Fine-tuned with LoRA/Unsloth on Indian legal corpus. Generates petitions, affidavits, notices, bail applications.',
  },
  {
    id: 'bge-small',
    name: 'bge-small (Retrieval)',
    purpose: 'Semantic legal retrieval',
    version: 'v1.5',
    provider: 'BAAI (Pre-trained)',
    status: 'available',
    latencyMs: 120,
    usageCount: 8834,
    lastUpdated: past(30),
    description: 'Embedding model for semantic search. Currently indexes 14,544 legal chunks in Supabase.',
  },
  {
    id: 'hallucination-classifier',
    name: 'Hallucination Classifier',
    purpose: 'Fact verification & grounding',
    status: 'coming_soon',
    description: 'Will verify AI-generated claims against retrieved evidence. Dataset preparation in progress.',
  },
];

// ── Clients ───────────────────────────────────────────────────────────────────

export const mockClients: Client[] = [
  {
    id: 'cl1',
    name: 'Ramesh Kumar',
    email: 'ramesh.kumar@gmail.com',
    phone: '+91 9812345678',
    type: 'individual',
    activeCases: 1,
    totalCases: 1,
    createdAt: past(120),
  },
  {
    id: 'cl2',
    name: 'Sharma Builders Pvt. Ltd.',
    email: 'legal@sharmabuilders.in',
    phone: '+91 11-23456789',
    type: 'organization',
    organization: 'Sharma Builders Pvt. Ltd.',
    activeCases: 1,
    totalCases: 3,
    createdAt: past(300),
  },
  {
    id: 'cl3',
    name: 'Vikas Nair',
    email: 'vnair.legal@gmail.com',
    phone: '+91 9999888777',
    type: 'individual',
    activeCases: 1,
    totalCases: 1,
    createdAt: past(200),
  },
  {
    id: 'cl4',
    name: 'M/s Tara Exports',
    email: 'accounts@taraexports.com',
    type: 'organization',
    organization: 'M/s Tara Exports',
    activeCases: 1,
    totalCases: 2,
    createdAt: past(400),
  },
  {
    id: 'cl5',
    name: 'TechNova Solutions Pvt. Ltd.',
    email: 'legal@technovasolutions.in',
    type: 'organization',
    organization: 'TechNova Solutions Pvt. Ltd.',
    activeCases: 1,
    totalCases: 1,
    createdAt: past(45),
  },
];

// ── Notifications ─────────────────────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'hearing_approaching',
    title: 'Hearing in 2 days',
    message: 'State vs. Vikas Nair — Bail application hearing at Delhi HC on ' + new Date(Date.now() + 2 * 86400000).toDateString(),
    caseId: 'c3',
    caseName: 'State vs. Vikas Nair',
    isRead: false,
    createdAt: past(0),
    actionUrl: '/cases/c3',
  },
  {
    id: 'n2',
    type: 'draft_ready',
    title: 'Draft ready for review',
    message: 'Bail Application for Vikas Nair has been generated and is awaiting your review.',
    caseId: 'c3',
    isRead: false,
    createdAt: past(1),
    actionUrl: '/drafts/dr1',
  },
  {
    id: 'n3',
    type: 'verification_warning',
    title: 'Verification alert',
    message: '1 claim in Bail Application (Vikas Nair) is only partially supported. Review before approval.',
    caseId: 'c3',
    isRead: false,
    createdAt: past(1),
    actionUrl: '/verification',
  },
  {
    id: 'n4',
    type: 'document_processed',
    title: 'Document processed',
    message: 'Counter Affidavit — UoI Response has been processed and entities extracted.',
    caseId: 'c1',
    isRead: true,
    createdAt: past(3),
  },
  {
    id: 'n5',
    type: 'task_assigned',
    title: 'Task assigned to you',
    message: 'Rahul Verma assigned: "File evidence bundle for Ramesh Kumar case"',
    caseId: 'c1',
    isRead: true,
    createdAt: past(3),
  },
];

// ── Analytics ─────────────────────────────────────────────────────────────────

export const mockAnalytics: AnalyticsOverview = {
  activeCases: 5,
  completedCases: 12,
  researchRequests: 47,
  draftsGenerated: 23,
  documentsProcessed: 89,
  avgProcessingTimeMs: 4800,
  verificationAlerts: 3,
};

export const mockCasesByStatus = [
  { label: 'Active', value: 5, color: '#1f6b45' },
  { label: 'Pending', value: 3, color: '#f4a261' },
  { label: 'Closed', value: 12, color: '#65736b' },
  { label: 'Stayed', value: 1, color: '#8b5cf6' },
];

export const mockCasesByType = [
  { label: 'Civil', value: 4, color: '#7ed957' },
  { label: 'Criminal', value: 3, color: '#e76f51' },
  { label: 'Family', value: 2, color: '#f4c95d' },
  { label: 'Consumer', value: 3, color: '#3b82f6' },
  { label: 'Corporate', value: 2, color: '#8b5cf6' },
  { label: 'Writ', value: 3, color: '#1f6b45' },
];

export const mockMonthlyActivity = [
  { label: 'Mar', cases: 2, docs: 8, research: 5, drafts: 3 },
  { label: 'Apr', cases: 3, docs: 12, research: 9, drafts: 5 },
  { label: 'May', cases: 1, docs: 15, research: 11, drafts: 6 },
  { label: 'Jun', cases: 4, docs: 18, research: 14, drafts: 8 },
  { label: 'Jul', cases: 2, docs: 22, research: 12, drafts: 7 },
  { label: 'Aug', cases: 3, docs: 14, research: 8, drafts: 5 },
];

// ── Team Members ──────────────────────────────────────────────────────────────

export const mockTeamMembers = [
  { id: 'tm1', name: 'Arjun Sharma', email: 'arjun@axiomlaw.in', role: 'lawyer', specialization: 'Constitutional Law', barCouncilId: 'DL/2015/12345', caseCount: 8 },
  { id: 'tm2', name: 'Priya Mehta', email: 'priya@axiomlaw.in', role: 'admin', specialization: 'Firm Administration', caseCount: 0 },
  { id: 'tm3', name: 'Rahul Verma', email: 'rahul@axiomlaw.in', role: 'junior', specialization: 'Civil Litigation', barCouncilId: 'DL/2022/67890', caseCount: 4 },
  { id: 'tm4', name: 'Sneha Patel', email: 'sneha@axiomlaw.in', role: 'junior', specialization: 'Criminal Law', barCouncilId: 'MH/2021/45678', caseCount: 3 },
  { id: 'tm5', name: 'Deepak Nair', email: 'deepak@axiomlaw.in', role: 'lawyer', specialization: 'Corporate Law', barCouncilId: 'KL/2013/23456', caseCount: 6 },
];
